version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - echo Installing...

  build:
    commands:
    - echo Building...
    - npm install
    - npm run webpack

artifacts:
  files:
  - index.html
  - babeldemo.html
  - favicon.ico
  - images/*
  - styles/*
  - dist/bundle.js

