version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Install ...

  build:
    commands:
      - echo Move along ... Nothing to see here

artifacts:
  files:
    - index.html
    - favicon.ico
    - images/*
    - styles/*

