version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - echo Installing ...

  build:
    commands:
    - echo Building ... Move along ... Nothing to see here

artifacts:
  files:
  - index.html
  - babeldemo.html
  - favicon.ico
  - images/*
  - styles/*

